---
output: html_fragment
---

<!--..........................................................................-->
<!--..........................................................................-->

```{r,include=FALSE}
knitr::opts_chunk$set(
  include = TRUE,
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10,
  fig.height = 8)
options(scipen=1)
```

```{r,include=FALSE}
library("devtools")
# devtools::install_github("ijlyttle/vembedr")
library("vembedr")
```

```{r,klippy, echo=FALSE, include=TRUE}
#See: https://rlesur.github.io/klippy/articles/klippy.html
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done', position = c('top', 'right'))
```

<!--..........................................................................-->
<!--..........................................................................-->

<hr />

<!--..........................................................................-->
# Using GRETL IDE
<!--..........................................................................-->

<hr />

<!--..........................................................................-->
## Introduction {.tabset .tabset-fade}
<!--..........................................................................-->

<hr />


<p class="head02">
Simple Data Manipulation
</p>

Learn how to change variable name, add variable description, generate new variable or delete a variable.
<br>
</br>

```{r, include=TRUE,echo=FALSE}
embed_url("https://youtu.be/qzR5w8_Ui9Q") %>%
    use_align("center")  %>%
    use_bs_responsive()
```


<!--..........................................................................-->
#
<!--..........................................................................-->


<!--..........................................................................-->
<!--..........................................................................-->

<!-- ## References -->

<!-- <hr /> -->

<!-- <p class="head01"> -->
<!-- References -->
<!-- </p> -->

<!--..........................................................................-->
## 
<!--..........................................................................-->

<!--..........................................................................-->
<hr />

<p class="back01">
[Back To *Start Software Implementation*](../../index.html)
</p>

<!--..........................................................................-->
<hr />





<!--..........................................................................--> 
<!-- THIS IS THE END --> 

<!-- Include bottom -->

````{=html}
```{r, include=TRUE, echo=FALSE, results='asis'}
xfun::file_string('bottom_01.html')
```
````